version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    pull_policy: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-root123}"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-root123}"
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "local:redis:6379"
    ports:
      - "8082:8081"
    depends_on:
      - redis

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin123}"
      POSTGRES_DB: "${POSTGRES_DB:-mydatabase}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    environment:
      CB_INIT_CONNECTION_NAME: "PostgreSQL"
      CB_INIT_CONNECTION_DRIVER: "postgresql"
      CB_INIT_CONNECTION_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB:-mydatabase}"
      CB_INIT_CONNECTION_USER: "${POSTGRES_USER:-admin}"
      CB_INIT_CONNECTION_PASSWORD: "${POSTGRES_PASSWORD:-admin123}"
    depends_on:
      - postgres

volumes:
  mongo_data:
  redis_data:
  postgres_data:
